apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  labels:
    app: search-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: nganeemmanuel/room8-searchservice:20250626061602
          ports:
            - containerPort: 8086
          env:
            - name: JAVA_OPTS
              value: "-Dspring.profiles.active=prod"
            - name: ELASTIC_URI
              valueFrom:
                secretKeyRef:
                  name: elastic-search-secret
                  key: elastic-uri
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: kafka-secret
                  key: kafka-bootstrap-servers
          envFrom:
            - configMapRef:
                name: search-service-config