apiVersion: v1
kind: Service
metadata:
  name: search-service
  labels:
    app: search-service
spec:
  selector:
    app: search-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8086
    - name: tcp
      protocol: TCP
      port: 8086
      targetPort: 8086
  type: ClusterIP