apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: nganeemmanuel/room8-authservice:20250605132141
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATA_REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-host
            - name: SPRING_DATA_REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-port
          envFrom:
            - configMapRef:
                name: auth-service-config