apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - name: tcp
      protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP