apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-registry:8761/eureka"
  SPRING_APPLICATION_NAME: "notification-service"
