apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8087
    - name: tcp
      protocol: TCP
      port: 8087
      targetPort: 8087
  type: ClusterIP