apiVersion: v1
kind: Service
metadata:
  name: bid-service
  labels:
    app: bid-service
spec:
  selector:
    app: bid-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8084
    - name: tcp
      protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP