apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-registry-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /eureka(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-registry
                port:
                  number: 8761
          - path: /eureka/
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-registry
                port:
                  number: 8761
