apiVersion: v1
kind: Service
metadata:
  name: service-registry
  labels:
    app: service-registry
spec:
  selector:
    app: service-registry
  ports:
    - name: tcp
      protocol: TCP
      port: 8761
      targetPort: 8761
    - name: http-monitor
      port: 8080
      targetPort: 8080
