apiVersion: v1
kind: Service
metadata:
  name: room-service
  labels:
    app: room-service
spec:
  selector:
    app: room-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8083
    - name: tcp
      protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP