apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-registry.default.svc.cluster.local:8761/eureka"
  SPRING_APPLICATION_NAME: "api-gateway"
