apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: search-service
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: base/search-service
    repoURL: https://github.com/NganeEmmanuel/room8-deployments
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
